export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const QUANTITY_HANDLER = 'QUANTITY_HANDLER';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const FETCH_CURRENCY_EXCHANGE_SUCCESS = 'FETCH_CURRENCY_EXCHANGE_SUCCESS';
export const FETCH_CURRENCY_EXCHANGE_FAILED = 'FETCH_CURRENCY_EXCHANGE_FAILED';

export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER_SUCCESS';
export const SUBMIT_ORDER_FAILED = 'SUBMIT_ORDER_FAILED';

export const RESET_SHOPPING_CART = 'RESET_SHOPPING_CART';
export const REMOVE_MESSAGE = 'REMOVE_MESSAGE';

export const FETCH_PREVIOUS_ORDERS_SUCCESS = 'FETCH_PREVIOUS_ORDERS_SUCCESS';
export const FETCH_PREVIOUS_ORDERS_FAILED = 'FETCH_PREVIOUS_ORDERS_FAILED';

export const START_LOADING_USER = 'START_LOADING_USER';
export const START_LOADING_ORDER = 'START_LOADING_ORDER';